# Generated by Django 5.2.7 on 2025-10-29 09:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0002_banner_created_by_banner_remark_banner_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTypeMaster',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accesstype_id', models.AutoField(primary_key=True, serialize=False)),
                ('accesstype_text', models.CharField(max_length=100)),
                ('access_type', models.CharField(max_length=20, unique=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AccessTypeMaster',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_name', models.CharField(max_length=50, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('blog_category', models.CharField(choices=[('travel_guide', 'Travel Guide'), ('adventure', 'Adventure'), ('food_dining', 'Food & Dining'), ('travel_tips', 'Travel Tips'), ('destinations', 'Destinations')], max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs_pics/')),
                ('keywords', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('description_1', models.TextField(blank=True, null=True)),
                ('description_2', models.TextField(blank=True, null=True)),
                ('description_3', models.TextField(blank=True, null=True)),
                ('description_4', models.TextField(blank=True, null=True)),
                ('srno', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('psrno', models.PositiveSmallIntegerField(blank=True, default=999, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='blogs', to='shreeswaroyasethapp.blogtag')),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserMaster',
            },
        ),
        migrations.CreateModel(
            name='UserTypeMaster',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usertype_id', models.AutoField(primary_key=True, serialize=False)),
                ('usertype_text', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=20, unique=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserTypeMaster',
            },
        ),
        migrations.CreateModel(
            name='UserMasterDetails',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usermasterdetail_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(auto_now_add=True, null=True)),
                ('to_date', models.DateField(blank=True, default=datetime.datetime(9999, 12, 31, 0, 0), null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('mobile', models.CharField(blank=True, max_length=300, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=300, null=True)),
                ('instagram', models.CharField(blank=True, max_length=300, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=300, null=True)),
                ('paid_or_free', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('last_login_on', models.DateTimeField(blank=True, null=True)),
                ('access_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shreeswaroyasethapp.accesstypemaster')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usermaster', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shreeswaroyasethapp.usermaster')),
                ('user_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shreeswaroyasethapp.usertypemaster', to_field='user_type')),
            ],
            options={
                'db_table': 'UserMasterDetails',
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
