# Generated by Django 5.2.7 on 2025-10-29 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0004_remove_blogpost_tags_blogpost_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ContactUs_id', models.AutoField(primary_key=True, serialize=False)),
                ('ContactUs_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('ContactUs_mobile_number_header', models.CharField(blank=True, max_length=255, null=True)),
                ('ContactUs_Emailid_header', models.CharField(blank=True, max_length=255, null=True)),
                ('ContactUs_logo', models.ImageField(blank=True, null=True, upload_to='BP')),
                ('ContactUs_Address1_head', models.CharField(blank=True, max_length=255, null=True)),
                ('ContactUs_Address1', models.TextField(blank=True, null=True)),
                ('ContactUs_Address2_head', models.CharField(blank=True, max_length=255, null=True)),
                ('ContactUs_Address2', models.TextField(blank=True, null=True)),
                ('ContactUs_EMAIL_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('ContactUs_Mobile_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('ContactUs_Whatsup_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Bio', models.TextField(blank=True, null=True)),
                ('Facebook', models.CharField(blank=True, max_length=300, null=True)),
                ('Instagram', models.CharField(blank=True, max_length=300, null=True)),
                ('Linkedin', models.CharField(blank=True, max_length=300, null=True)),
                ('Youtube', models.CharField(blank=True, max_length=300, null=True)),
                ('ContactUs_Form_EMAIL', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('footer_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ContactUs',
            },
        ),
    ]
