# Generated by Django 5.2.7 on 2025-10-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0006_remove_blogpost_created_at_aboutus_banner_citymaster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='accesstypemaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='blogtag',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='citymaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contectussubmit',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hotelamenity',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hotelhighlight',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hotelmaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hotelrating',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hotelroomtype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='servicedetailmaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='servicefeature',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='servicehighlightmaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tourfacility',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='touritinerarymaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tourmaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tourratingmaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tourspecificationmaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermasterdetails',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usertypemaster',
            name='is_active',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='accesstypemaster',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='citymaster',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='contactus',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='contectussubmit',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='faq',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelamenity',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelhighlight',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelmaster',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelrating',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelroomtype',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='servicedetailmaster',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='servicehighlightmaster',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='slider',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='tourfacility',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='touritinerarymaster',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='tourmaster',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='tourratingmaster',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='tourspecificationmaster',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='usermasterdetails',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='usertypemaster',
            name='record_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
    ]
