# Generated by Django 5.2.7 on 2025-10-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0007_remove_aboutus_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_sub_titile',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_titile',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
