# Generated by Django 5.2.7 on 2025-10-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0008_banner_banner_sub_titile_banner_banner_titile'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymaster',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
