# Generated by Django 5.2.7 on 2025-10-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0009_citymaster_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymaster',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
