# Generated by Django 5.2.7 on 2025-10-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0010_alter_citymaster_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='ContactUs_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
