# Generated by Django 5.2.7 on 2025-10-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0011_contactus_contactus_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='ContactUs_Mobile_Number',
            new_name='ContactUs_Mobile_Number_1',
        ),
        migrations.AddField(
            model_name='contactus',
            name='ContactUs_Mobile_Number_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
