# Generated by Django 5.2.7 on 2025-10-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0012_rename_contactus_mobile_number_contactus_contactus_mobile_number_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='footer_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
