# Generated by Django 5.2.7 on 2025-10-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0013_alter_contactus_footer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Working_Hours_Time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='Working_Hours_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
