# Generated by Django 5.2.7 on 2025-10-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0014_contactus_working_hours_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmaster',
            name='duration',
            field=models.CharField(blank=True, help_text="Example: '5 Days / 4 Nights'", max_length=100, null=True),
        ),
    ]
