# Generated by Django 5.2.7 on 2025-10-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0016_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='country',
        ),
    ]
