# Generated by Django 5.2.7 on 2025-10-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0018_remove_blogpost_tag_blogtag_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtag',
            old_name='tag',
            new_name='blog',
        ),
    ]
