# Generated by Django 5.2.7 on 2025-11-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0020_blogpost_created_at_blogpost_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_category',
            field=models.CharField(choices=[('travel guide', 'Travel Guide'), ('adventure', 'Adventure'), ('food dining', 'Food & Dining'), ('travel tips', 'Travel Tips'), ('destinations', 'Destinations')], max_length=50),
        ),
    ]
