# Generated by Django 5.2.7 on 2025-11-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0021_alter_blogpost_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs_banner/'),
        ),
    ]
