# Generated by Django 5.2.7 on 2025-11-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0022_blogpost_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog_image',
            new_name='banner_image',
        ),
    ]
