# Generated by Django 5.2.7 on 2025-11-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0023_rename_blog_image_blogpost_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemaster',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
