# Generated by Django 5.2.7 on 2025-11-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0024_servicemaster_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
