# Generated by Django 5.2.7 on 2025-11-01 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0025_alter_servicemaster_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroomtype',
            name='bed_type',
        ),
        migrations.RemoveField(
            model_name='hotelroomtype',
            name='features',
        ),
        migrations.RemoveField(
            model_name='hotelroomtype',
            name='size',
        ),
        migrations.RemoveField(
            model_name='hotelroomtype',
            name='view_type',
        ),
        migrations.CreateModel(
            name='HotelRoomTypefeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('record_status', models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20)),
                ('features', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('hotelroomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HotelRoomTypefeatures', to='shreeswaroyasethapp.hotelroomtype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HotelRoomTypefeatures',
                'ordering': ['-created_at'],
            },
        ),
    ]
