# Generated by Django 5.2.7 on 2025-11-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0026_remove_hotelroomtype_bed_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomtype',
            name='on_basis',
            field=models.CharField(choices=[('per person', 'Per Person'), ('per day', 'Per Day'), ('per night', 'Per Night'), ('per group', 'Per Group')], default='per_night', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelmaster',
            name='on_basis',
            field=models.CharField(choices=[('per person', 'Per Person'), ('per day', 'Per Day'), ('per night', 'Per Night'), ('per group', 'Per Group')], default='per_night', max_length=50),
        ),
    ]
