# Generated by Django 5.2.7 on 2025-11-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0027_hotelroomtype_on_basis_alter_hotelmaster_on_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomtype',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR (₹)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)')], default='INR', max_length=10),
        ),
    ]
