# Generated by Django 5.2.7 on 2025-11-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0028_hotelroomtype_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='customer_satisfaction',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='happy_travelers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='uae_branches',
            field=models.PositiveIntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, max_length=255, null=True),
        ),
    ]
