# Generated by Django 5.2.7 on 2025-11-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0029_alter_aboutus_customer_satisfaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='customer_satisfaction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='uae_branches',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='years_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
