# Generated by Django 5.2.7 on 2025-11-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0031_alter_aboutus_short_description_whychooseus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contectussubmit',
            name='ContectUs_Destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contectussubmit',
            name='ContectUs_cono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contectussubmit',
            name='ContectUs_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contectussubmit',
            name='ContectUs_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contectussubmit',
            name='ContectUs_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
