# Generated by Django 5.2.7 on 2025-11-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0032_alter_contectussubmit_contectus_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymaster',
            name='city_sort_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
