# Generated by Django 5.2.7 on 2025-11-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0033_citymaster_city_sort_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='tag_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
