# Generated by Django 5.2.7 on 2025-11-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0035_alter_tourmaster_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmaster',
            name='package_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
