# Generated by Django 5.2.7 on 2025-11-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0036_tourmaster_package_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourmaster',
            name='on_basis',
            field=models.CharField(blank=True, choices=[('per person', 'Per Person'), ('per day', 'Per Day'), ('per night', 'Per Night'), ('per group', 'Per Group')], default='per_person', max_length=50, null=True),
        ),
    ]
