# Generated by Django 5.2.7 on 2025-11-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0037_alter_tourmaster_on_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritinerarymaster',
            name='day_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
