# Generated by Django 5.2.7 on 2025-11-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0038_alter_touritinerarymaster_day_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmaster',
            name='hotel_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='service_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
