# Generated by Django 5.2.7 on 2025-11-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shreeswaroyasethapp', '0041_termsandcondition_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmaster',
            name='currency',
            field=models.CharField(choices=[('INR', '₹'), ('USD', '$'), ('EUR', '€'), ('GBP', '£')], default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotelmaster',
            name='on_basis',
            field=models.CharField(choices=[('Per Person', 'Per Person'), ('Per Day', 'Per Day'), ('Per Night', 'Per Night'), ('Per Group', 'Per Group')], default='Per Night', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelroomtype',
            name='currency',
            field=models.CharField(choices=[('INR', '₹'), ('USD', '$'), ('EUR', '€'), ('GBP', '£')], default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotelroomtype',
            name='on_basis',
            field=models.CharField(choices=[('Per Person', 'Per Person'), ('Per Day', 'Per Day'), ('Per Night', 'Per Night'), ('Per Group', 'Per Group')], default='Per Night', max_length=50),
        ),
        migrations.AlterField(
            model_name='tourmaster',
            name='currency',
            field=models.CharField(blank=True, choices=[('INR', '₹'), ('USD', '$'), ('EUR', '€'), ('GBP', '£')], default='INR', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tourmaster',
            name='on_basis',
            field=models.CharField(blank=True, choices=[('Per Person', 'Per Person'), ('Per Day', 'Per Day'), ('Per Night', 'Per Night'), ('Per Group', 'Per Group')], default='per_person', max_length=50, null=True),
        ),
    ]
